### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by gibraltar**
Updated to include the latest Couchbase scopes and collection options. @daffl please update the generators after this is merged, to make sure that these features become available upon service creation

Andrei

### CODE REVIEW

**Comment by frank-dspeed** [comment]
@gibraltar It will take some time i need to squash your commits and verify that they are working

**Comment by gibraltar** [comment]
> @gibraltar It will take some time i need to squash your commits and verify that they are working

Sounds good ! I have forked the version onto our repository, so we can use our github for now, until this one is merged.

**Comment by frank-dspeed** [comment]
@gibraltar so all is working as expected in your case?

**Comment by frank-dspeed** [comment]
Closed by: #71

**Comment by gibraltar** [comment]
> @gibraltar so all is working as expected in your case?

Absolutely I have tested it and it works. Like I said the only thing we have to do or Dave has to do to enable the scopes and collections to appear in the service file is to update the generator templates.

The current implementation is backwards compatible so it’s not going to break the existing code, but all pick the default scope and collections. But you can override it manually by adding “scope” and/or “collection” in the service options.

**Comment by gibraltar** [comment]
> @gibraltar so all is working as expected in your case?

So the next step after this is merged we can update the generator function and templates, to say something like this:

“Please enter the bucket name”
…
“Please enter the scope name”
….
“Please answer the collection name”
….

In each case the default scope and the default collection will be in _default. If you just press enter.

Right now everything would work just like it was before except you would have to manually enter those two values inside the options of the service.

**Pull request closed without merging**
